<?php
/**
 * ACF fields
 * 
 * Register of all custom fields from ACF
 * 
 * For more info: https://www.advancedcustomfields.com/resources/register-fields-via-php/
 * 
 */


if( function_exists('acf_add_local_field_group') ):

    //Theme Options
    acf_add_local_field_group(array(
        'key' => 'group_5c6eb2a157f0c',
        'title' => 'Opções do Tema',
        'fields' => array(
            // Header
            array(
                'key' => 'field_60821923b28cf12',
                'label' => 'Header',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_606ba4a8e1bd0',
                'label' => 'Logos e bg',
                'name' => 'option_header',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_606ba543e1bd2',
                        'label' => 'Logo',
                        'name' => 'option_logo',
                        'type' => 'image',
                        'instructions' => 'Selecione a logo ou faça o upload da imagem!',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => 2,
                        'mime_types' => 'jpg,png,svg',
                    ),
                    array(
                        'key' => 'field_606ba82e462fd',
                        'label' => 'Imagem de fundo do menu mobile',
                        'name' => 'option_bg_menu_mobile',
                        'type' => 'image',
                        'instructions' => 'Selecione a imagem para o fundo do menu mobile.',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'url',
                        'preview_size' => 'medium',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => 2,
                        'mime_types' => '',
                    ),
                    array(
                        'key' => 'field_606ba5a5a32bd3',
                        'label' => 'Cor de fundo do menu mobile',
                        'name' => 'option_header_bg_mobile',
                        'type' => 'color_picker',
                        'instructions' => 'Selecione a cor do fundo.( Opcional )',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                    ),
                    array(
                        'key' => 'field_606ba5a5e1bd3',
                        'label' => 'Cor de fundo',
                        'name' => 'option_header_bg',
                        'type' => 'color_picker',
                        'instructions' => 'Selecione a cor do fundo.( Opcional )',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                    ),
                    array(
                        'key' => 'field_5c6eb3a46bb18',
                        'label' => 'Favicon',
                        'name' => 'favicon',
                        'type' => 'image',
                        'instructions' => 'Aqui você irá inserir o favicon do site',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'url',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                    array(
                        'key' => 'field_60709201f574d',
                        'label' => 'Link externo',
                        'name' => 'linkdepo',
                        'type' => 'link',
                        'instructions' => 'Insira o link do botão para direcionamento externo',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                    ),
                ),
            ),
            // Contatos
            array(
                'key' => 'fid_60821923b28cf12a',
                'label' => 'Footer',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_citend',
                'label' => 'Endereço',
                'name' => 'cit_end',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 3,
                'new_lines' => 'br',
            ),
            array(
                'key' => 'field_telefone',
                'label' => 'Telefones',
                'name' => 'telefones',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 3,
                'new_lines' => 'br',
            ),
            array(
                'key' => 'field_email',
                'label' => 'Email',
                'name' => 'footer_mail',
                'type' => 'text',
                'instructions' => 'Insira o título',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '33',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            // Redes sociais
            array(
                'key' => 'field_60821923b28a',
                'label' => 'Redes socias',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_606baba14fdac',
                'label' => 'Social',
                'name' => 'option_midias',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_606baa2105921',
                        'label' => 'Redes sociais',
                        'name' => 'option_redes_sociais',
                        'type' => 'repeater',
                        'instructions' => 'Selecione as redes sociais',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'collapsed' => 'field_606baa4005922',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'table',
                        'button_label' => 'Adicionar rede social',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_606baa4005922',
                                'label' => 'Rede social',
                                'name' => 'sociais_midia',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'facebook' => 'Facebook',
                                    'messenger' => 'Messenger',
                                    'youtube' => 'YouTube',
                                    'whatsApp' => 'WhatsApp',
                                    'instagram' => 'Instagram',
                                    'linkedin' => 'LinkedIn',
                                    'tikTok' => 'TikTok',
                                    'snapchat' => 'Snapchat',
                                    'pinterest' => 'Pinterest',
                                    'telegram' => 'Telegram',
                                    'twitter' => 'Twitter',
                                ),
                                'default_value' => false,
                                'allow_null' => 0,
                                'multiple' => 0,
                                'ui' => 1,
                                'ajax' => 1,
                                'return_format' => 'array',
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_606babdfad479',
                                'label' => 'Url da rede social',
                                'name' => 'sociais_url',
                                'type' => 'url',
                                'instructions' => 'Insira o link para a rede social',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => 'http://www.facebook.com',
                            ),
                        ),
                    ),
                ),
            ), 
            //newsletter
            array(
                'key' => 'field_bhdgd5',
                'label' => 'Newsletter',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),  
            array(
                'key' => 'field_news_title',
                'label' => 'Título',
                'name' => 'news_title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ), 
            array(
                'key' => 'field_news_desc',
                'label' => 'Descrição',
                'name' => 'news_desc',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 3,
                'new_lines' => 'br',
            ),  
            array(
                'key' => 'field_news_form',
                'label' => 'Formulário',
                'name' => 'news_form',
                'type' => 'post_object',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array(
                    0 => 'wpcf7_contact_form',
                ),
                'taxonomy' => '',
                'allow_null' => 0,
                'multiple' => 0,
                'return_format' => 'object',
                'ui' => 1,
            ),   
            //Banco de ideias
            array(
                'key' => 'field_bancoid',
                'label' => 'Banco de Ideias',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),     
            array(
                'key' => 'field_news_ideias',
                'label' => 'Título',
                'name' => 'bc_title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_ideias_desc',
                'label' => 'Descrição',
                'name' => 'bc_desc',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => 3,
                'new_lines' => 'br',
            ),
            array(
                'key' => 'field_6082ab9c',
                'label' => 'Link',
                'name' => 'bc_link',
                'type' => 'link',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'theme-options',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    $pages = [
        'home'    
    ];

    foreach ($pages as $page) {
        require get_template_directory() . '/includes/acf-pages/'.$page.'.php';
    }

endif;

